### ISSUE TITLE
history graph continuously grows

### ISSUE THREAD

**Issue by dmd** [jabyrd3/dashboard-from-scratch#14]
The history graph continuously grows to the right as new data arrives.

**Comment by dmd** [comment]
<img width="939" alt="screenshot 2017-05-30 08 52 28" src="https://cloud.githubusercontent.com/assets/41439/26584050/792c9252-4515-11e7-8229-512fe956200e.png">

**Comment by jabyrd3** [comment]
@dmd pull and try it again, i think i fixed it.

**Comment by dmd** [comment]
You forgot to push

**Comment by jabyrd3** [comment]
done

**Comment by dmd** [comment]
![image](https://cloud.githubusercontent.com/assets/41439/26639821/dd43bcc8-45f3-11e7-9c41-787674b65135.png)

lol no. this is how it STARTS now.

**Comment by jabyrd3** [comment]
Can you send me fresh data?

On Wed, May 31, 2017 at 11:25 AM "Daniel M. Drucker"

<
mailto:
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

https://cloud.githubusercontent.com/assets/41439/26639821/dd43bcc8-45f3-11e7-9c41-787674b65135.png

lol no. this is how it STARTS now.

—

You are receiving this because you commented.

Reply to this email directly,
https://github.com/jabyrd3/dashboard-from-scratch/issues/14#issuecomment-305222906
, or

**Comment by dmd** [comment]
[data.txt](https://github.com/jabyrd3/dashboard-from-scratch/files/1042081/data.txt)
[history.txt](https://github.com/jabyrd3/dashboard-from-scratch/files/1042082/history.txt)

**Comment by dmd** [comment]
Closed by c912904871ae7ec0e4511a14541dfc10addc9b64
